export const webinars = [
  {
    id: 1,
    slug: "introduction-to-machine-learning",
    title: "Introduction to Machine Learning",
    description: "Join us for an introductory webinar on machine learning techniques and applications.",
    thumbnail: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
    date: "2024-03-10",
    category: "Machine Learning",
    host: "AI Academy",
    content: [
      {
        id: 1,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Understanding Machine Learning Concepts",
        description: "Learn about supervised and unsupervised learning, classification, regression, and more.",
      },
      {
        id: 2,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Real-world Applications of Machine Learning",
        description: "Explore how machine learning is used in industries such as healthcare, finance, and marketing.",
      },
    ],
  },
  {
    id: 2,
    slug: "python-for-data-science",
    title: "Python for Data Science",
    description: "Join us for a webinar that introduces Python programming for data analysis and visualization.",
    thumbnail: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
    date: "2024-03-15",
    category: "Data Science",
    host: "Data Science Society",
    content: [
      {
        id: 1,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Introduction to Python Programming",
        description: "Learn the basics of Python syntax, data types, and control structures.",
      },
      {
        id: 2,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Data Manipulation and Visualization with Python",
        description: "Explore libraries like NumPy, Pandas, and Matplotlib for data manipulation and visualization.",
      },
    ],
  },
  {
    id: 3,
    slug: "deep-learning-fundamentals",
    title: "Deep Learning Fundamentals",
    description: "Join us to explore the basics of deep learning and neural networks.",
    thumbnail: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
    date: "2024-03-20",
    category: "Deep Learning",
    host: "Deep Learning Institute",
    content: [
      {
        id: 1,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Introduction to Neural Networks",
        description: "Understand the basic structure of neural networks and how they are trained.",
      },
      {
        id: 2,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Deep Learning Architectures",
        description: "Learn about popular deep learning architectures like CNNs, RNNs, and GANs.",
      },
    ],
  },
  {
    id: 4,
    slug: "data-visualization-with-d3",
    title: "Data Visualization with D3.js",
    description: "Learn to create interactive data visualizations using D3.js.",
    thumbnail: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
    date: "2024-03-25",
    category: "Data Visualization",
    host: "Visualization Society",
    content: [
      {
        id: 1,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Getting Started with D3.js",
        description: "Get introduced to the basics of D3.js and its data-driven approach to DOM manipulation.",
      },
      {
        id: 2,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Creating Interactive Visualizations",
        description: "Learn to add interactivity to your visualizations with D3.js events and transitions.",
      },
    ],
  },
  {
    id: 5,
    slug: "cloud-computing-fundamentals",
    title: "Cloud Computing Fundamentals",
    description: "Discover the basics of cloud computing and its benefits for businesses.",
    thumbnail: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
    date: "2024-03-30",
    category: "Cloud Computing",
    host: "Cloud Academy",
    content: [
      {
        id: 1,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Introduction to Cloud Computing",
        description: "Understand the concept of cloud computing and its key characteristics.",
      },
      {
        id: 2,
        img: "https://www.shutterstock.com/image-photo/businessman-team-work-using-laptop-260nw-1545205661.jpg",
        title: "Cloud Service Models",
        description: "Learn about IaaS, PaaS, and SaaS, and their differences and use cases.",
      },
    ],
  },
];
